### ISSUE TITLE
Purpose of app.resolver.ts?

### ISSUE THREAD

**Issue by dhnm** [marcjulian/nestjs-prisma-nexus#4]
I tried removing it and everything still works.

**Comment by marcjulian** [comment]
`app.resolver.ts` is only an example graphql query and has currently now purpose. You can delete it or add new queries/mutations to the class.

**Comment by marcjulian** [comment]
I can recommend you checking out [Nest Prisma Starter](https://github.com/fivethree-team/nestjs-prisma-starter). This project was only to test if nest works with prisma-nexus.

In this project I am using [Nest Prisma Starter](https://github.com/fivethree-team/nestjs-prisma-starter) [typegraphql](https://typegraphql.ml/) which is recommended for [nest](https://docs.nestjs.com/graphql/quick-start#code-first). Also typegraphql announced an integration with the upcoming prisma2 release, you can follow the issue here [Typegraphql Prisma Integration](https://github.com/MichalLytek/type-graphql/issues/476)
